<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="TestCreateDelHotZoneFirefox-20160307104646" tests="1" time="71.278">
	<testcase classname="TestCreateDelHotZoneFirefox" name="test_create_del_hotzone_firefox" time="71.278">
		<error message="Alert Text: None
&lt;super: &lt;class 'WebDriverException'&gt;, &lt;UnexpectedAlertPresentException object&gt;&gt;" type="UnexpectedAlertPresentException">
<![CDATA[Traceback (most recent call last):
  File "test_create_del_hotzone_firefox.py", line 58, in test_create_del_hotzone_firefox
    driver.find_element_by_xpath("//button[@type='button']").click()
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 258, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
UnexpectedAlertPresentException: Alert Text: None
<super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>>
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
